openapi: 3.0.0
info:
  title: API NetLeak
  version: 1.0.0
servers:
  - url: http://localhost:8081/
components:
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /v1/api/signup:
    post:
      summary: Register a new user (Send email inform)
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  default: trannhutphattv@gmail.com
                password:
                  type: string
                  default: 123456
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                    default: 65e9bfd4facc450c979573ea
                  email:
                    type: string
                    default: trannhutphattv@gmail.com
        201:
          description: User already exists
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: integer
                    default: 201
                  message:
                    type: string
                    default: User already exists
  /v1/api/login:
    post:
      summary: Login a user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  default: trannhutphattv@gmail.com
                password:
                  type: string
                  default: 123456
      responses:
        200:
          description: OK
          content:
            application/json:
             schema:
                items: 
                  type: object
                  properties:
                    user:
                      type: object
                      properties:
                        id:
                          type: string
                          default: 65e9bfd4facc450c979573ea
                        email:
                          type: string
                          default: trannhutphattv@gmail.com
                        favorites:
                          type: array
                          default: []
                        roles:
                          type: array
                          default: ["user"]
                    accessToken: 
                      type: string
                      default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZWE5NGY1MDUwMThmZjYzYTJmNDc2OSIsImVtYWlsIjoibmh1dHBoYXR0cmFucGhAZ21haWwuY29tIiwiaWF0IjoxNzA5ODc0NDk3LCJleHAiOjE3MDk4OTI0OTd9.DV0VSw2jkUQ88kpqUP3yyyreDVOpXiEMk0Z4kkHYjYo
        201:
          description: User not registered
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: integer
                    default: 201
                  messgage: 
                    type: string
                    default: User not registered
        401:
          description: Wrong Password
          content:
            application/json:
              schema:
                properties:
                  statusCode:
                    type: integer
                    default: 401
                  messgage: 
                    type: string
                    default: Wrong Password
  /v1/api/refreshToken:
    post:
      summary: Get a new access token
      tags:
        - Auth
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  accessToken:
                    type: string
                    default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZWMzYWM2ODU0NGE3ZjFlNGM3NjE2MCIsImVtYWlsIjoibmh1dHBoYXR0cmFucGhAZ21haWwuY29tIiwiaWF0IjoxNzEwMDg1Mzg4LCJleHAiOjE3MTAwODU0MTh9.T_oz89fEBUNJfSQw_oMxmsVWqpsCG5BNX8qfJYzrjLM
                  user:
                    properties:
                      id:
                        type: string
                        default: 65ec3ac68544a7f1e4c76160
                      email:
                        type: string
                        default: trannhutphattv@gmail.com
  /v1/api/user/listAllUsers:
    get:
      security:
        - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        description: An authorization header with access_token, ex - Bearer {accessToken get from login}
      summary: List all users
      tags:
        - User
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    _id:
                      type: string
                      default: 65ea94f505018ff63a2f4769
                    email:
                      type: string
                      default: nhutphattranph@gmail.com
                    favorites: 
                      type: array
                      default: []
                    roles:
                      type: array
                      default: ["user"]
  /v1/api/user/updatePassword:
    patch:
      security:
        - bearerAuth: []
      parameters:
      - name: Authorization
        in: header
        description: An authorization header with access_token, ex - Bearer {accessToken get from login}
      summary: update password for user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                id:
                  type: string
                  default: 65edf7925e8b0ce8a8f23499
                password:
                  type: string
                  default: 123456
      responses:
        200:
          description: OK
          content:
            appication/json:
              schema:
                properties:
                  message:
                    type: string
                    default: "Update password successfully"
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        default: 65e9bfd4facc450c979573ea
                      email:
                        type: string
                        default: trannhutphattv@gmail.com
                      favorites:
                        type: array
                        default: []
                      roles:
                        type: array
                        default: ["user"]